continents/urls.py
from django.contrib import admin
from django.urls import path
from continents.views import ContinentsView, ContinentsIdDetailView

app_name='continents'

urlpatterns = [
    path("", ContinentsView.as_view(), name="home"),
    path("<int:id>/", ContinentsIdDetailView.as_view(), name="id_detail")
]

countries/urls.py
from django.contrib import admin
from django.urls import path
from countries.views import (CountryDetailView,CountryIdDetailView)

app_name = 'countries'

urlpatterns = [
    path("<int:id>/", CountryIdDetailView.as_view(), name="id_detail"),
    path("<code>/", CountryDetailView.as_view(), name="code_detail"),
]

geographic/urls.py
from django.contrib import admin
from django.urls import path, include
#Function Based View
"""from countries.views import home"""
#Class Based View
"""from countries.views import HomeView"""
##Comportamiento por defecto
from countries.views import (HomeView, UniformView)

urlpatterns = [
    path('admin/', admin.site.urls),
    #Vistas basadas en Funciones (Function Based View)
    #path("", home)

    #Class Based View
    #path("", HomeView.as_view())
    ##Comportamiento por defecto
    path("", HomeView.as_view(), name="home"),
    path("uniform/", UniformView.as_view(), name="uniform"),
    path("continents/", include("continents.urls", namespace="continents")),
    path("countries/", include("countries.urls", namespace="countries"))
]

continents/models.py
from django.db import models

# Create your models here.

continents/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class ContinentsView(TemplateView):
    template_name = 'continents/continents.html'

class ContinentsIdDetailView(TemplateView):
	template_name = 'continents/continents_id_detail.html'

	def get_context_data(self, *args, **kwargs):
		code_id = kwargs['id']
		return {'id': code_id}

countries/views.py
from django.shortcuts import render
from django.http import HttpResponse
"""from django.views.generic import View"""
##Comportamiento por defecto
from django.views.generic import TemplateView

#Vistas basadas en Funciones (Function Based View)
"""def home(request):
	return render(request, 'countries/home.html')"""

#Vistas basadas en Clases (Class Based View)
#class HomeView(View):
##Comportamiento por defecto
class HomeView(TemplateView):
	#Dependiendo el tipo de respuesta que necesitemos implementamos la funcion
	#get o post
	#def get(self, request, *args, **kwargs):
	#	return render(request, 'countries/home.html')
	##Comportamiento por defecto
	template_name = 'countries/home.html'

class UniformView(TemplateView):
	template_name = 'countries/uniform.html'

class CountryDetailView(TemplateView):
	template_name = 'countries/country_detail.html'

	def get_context_data(self, *args, **kwargs):
		code = kwargs['code']
		return {'code': code}

class CountryIdDetailView(TemplateView):
	template_name = 'countries/country_id_detail.html'

	def get_context_data(self, *args, **kwargs):
		code_id = kwargs['id']
		return {'id': code_id}

continents/templates/continents/continents.html
{% extends "countries/base.html" %}
{% block title %}Continents{% endblock %}
{% block content %}

{% include "countries/intro.html" %}
      {% for continent in continents %}
      <div class="border block_country" align="center">
        <a href="{{continents.detail_url}}"><h2>{{continent.name}}</h2></a>
        <p>
          <strong>Cantidad de equipos clasificados: </strong>
          {{continent.quantity}}
        </p>
        <p>
          <strong>Equipos que alcanzaron las semifinal: </strong>
          {{continent.semifinalist}}
        </p>
      </div>
      {% endfor %}

{% endblock %}

continents/templates/continents/continents_id_detail.html
{% extends "countries/base.html" %}
{% block title %}{{continent.name}}{% endblock %}
{% block content %}
<div class="detail" align="center">
  {% for continent in continents %}
      {% if continent.id == id %}
        <h1>{{continent.name|title}}</h1>
      {% endif %}
  {% endfor %}
  <a href="{% url "continents:home" %}">Continentes</a>
</div>
{% endblock %}

countries/templates/countries/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Geo{% endblock %}</title>
  </head>
  <body style="margin: 0 0 0 0;">
  <style media="screen">
    .header {
      border: 1px solid #212121;
      margin: 0 0 0 0;
      text-align: center;
      padding: 20px 20px 20px 20px;
      background-color: #607D8B;
    }
    .content {
      padding-top: 0px;
    	padding-bottom: 20px;
    	padding-left: 50px;
    	padding-right: 50px;
    }
    .border{
      border: 1px solid #212121;
    }

    .block_country{
      display: inline-block;
      padding-right: 20px;
      padding-left: 20px;
    }

    .detail{
      padding-top: 30px
    }

    .breadcrumb{
      margin-top: 15px;
      padding-left: 20px;
      padding-right: 20px;
    }
  </style>
    <div class="header">
      <a href="{% url "home" %}">
        <h3>Geographic</h3>
      </a>
    </div>
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

countries/templates/countries/breadcrumbs.html
<div align="center">
  {% for country in countries %}
    <div class="breadcrumb border block_country" align="center" display="inline">
      <a href="{% url "countries:code_detail" code=country.code %}">{{country.name}}</a>
    </div>
  {% endfor %}
</div>

countries/templates/countries/country_detail.html
{% extends "countries/base.html" %}
{% block title %}{{code}}{% endblock %}
{% block content %}
{% include "countries/intro.html" %}
{% include "countries/breadcrumbs.html" %}
<div class="detail" align="center">
  {% for country in countries %}

      {% if country.code == code %}
        <h1>{{country.name|title}} ({{code}})</h1>
        <img src="{{country.map}}" alt="">
        <img src="{{country.uniform}}" height="200" alt="">
        <h3>{{country.pos}}</h3>
      {% endif %}

  {% endfor %}
</div>
{% endblock %}

countries/templates/countries/country_id_detail.html
{% extends "countries/base.html" %}
{% block title %}{{code}}{% endblock %}
{% block content %}
{% include "countries/intro.html" %}
{% include "countries/breadcrumbs.html" %}
<div class="detail" align="center">
  {% for country in countries %}

      {% if country.id == id %}
        <h1>{{country.name|title}} ({{country.code}})</h1>
        <img src="{{country.map}}" alt="">
        <img src="{{country.uniform}}" height="200" alt="">
        <h3>{{country.pos}}</h3>
      {% endif %}

  {% endfor %}
</div>
{% endblock %}

countries/templates/countries/home.html
{% extends "countries/base.html" %}
{% block title %}Inicio - Geo{% endblock %}
{% block content %}

{% include "countries/intro.html" %}

	{% comment %}
	Template Tags With Jinja:
	Podemos usar como vemos más abajo:
	* for
	* if
	* lorem ipsum (generador)
	* now (fecha actual)
	* comment (comentarios)
	Filters
	* title : combierte la primera letra de cada palabra en mayuscula
	* force_scape : elimina los caracteres especiales
	* lower: pone las letras en minuscula

	https://docs.djangoproject.com/en/dev/ref/templates/builtins/
	{% endcomment %}

	{% for country in countries %}
		<div align="center">
			<a href="{% url "countries:code_detail" code=country.code %}">
				<h3>{{country.name|title}}</h3>
			</a>
			{% if country.pos == 'Campeón' %}
				<p>🏆</p>
			{% endif %}
			<p>{{country.pos}}</p>
			<img src="{{country.map}}" height="200" alt="">
		</div>
		<p>{% lorem %}</p>
	{% endfor %}
	<h3>{% filter force_escape|lower %}
    rUSIA 2018 - FIFA
	{% endfilter %}</h3>
{% endblock %}

countries/templates/countries/intro.html
<div class="border" align="center">
  <h1>Los Mejores Paises</h1>
  <h2>En la Copa del Mundo 2018</h2>
  <p>
    <strong>Logged as: </strong>
    {{request.user}}
  </p>
  <h3>{% now "Y-m-d"%}</h3>
  <div align="center">
      <div class="breadcrumb border block_country" align="center" display="inline">
        <p><a href="{% url "uniform" %}">Uniformes</a></p>
      </div>
      <div class="breadcrumb border block_country" align="center" display="inline">
        <p><a href="{% url "home" %}">Inicio</a></p>
      </div>
      <div class="breadcrumb border block_country" align="center" display="inline">
        <p><a href="{% url "continents:home" %}">Continentes</a></p>
      </div>
  </div>

</div>

countries/templates/countries/uniform.html
{% extends "countries/base.html" %}
{% block title %}Uniform - Geo{% endblock %}
{% block content %}
{% include "countries/intro.html" %}
<div align="center">
  {% for country in countries %}
  <div class="block_country">
    <h2>{{country.name|title}}</h2>
    <a href="{% url "countries:id_detail" id=country.id %}">
      <img src="{{country.uniform}}" height="100" alt="">
    </a>
  </div>
  {% endfor %}
  <p><a href="/">Inicio</a></p>
</div>
{% endblock %}